[project]
name = "backup-bot"
version = "0.1.0"
description = "A Custom bot for backing up Discord threads/channels"
readme = "README.md"
requires-python = ">=3.14"
dependencies = [
    "aiofiles>=25.1.0",
    "discord-py>=2.7.1",
    "dotenv>=0.9.9",
]

[project.scripts]
backup-bot = "backup_bot:main"

[build-system]
requires = ["uv_build>=0.12.19,<0.13.0"]
build-backend = "uv_build"
